plugins {
    id "com.android.application"
    id "com.google.gms.google-services"
}

android {
    namespace "com.casadekebab.smsgateway"
    compileSdk 35

    defaultConfig {
        applicationId "com.casadekebab.smsgateway"
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "1.1.0"
    }
}

dependencies {
    implementation platform("com.google.firebase:firebase-bom:34.7.0")
    implementation "com.google.firebase:firebase-messaging"

    implementation "androidx.work:work-runtime:2.11.1"
}