# Generated by Django 5.2.15 on 2026-06-10 19:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, default='', max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name_es'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('default_address', models.TextField(blank=True, default='')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=8)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_text', models.TextField()),
                ('city', models.CharField(default='Salamanca', max_length=120)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='restaurant.customer')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, default='', max_length=160)),
                ('description_es', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurant.category')),
            ],
            options={
                'ordering': ['category__sort_order', 'sort_order', 'name_es'],
            },
        ),
        migrations.CreateModel(
            name='MenuOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.CharField(max_length=120)),
                ('title_en', models.CharField(blank=True, default='', max_length=120)),
                ('required', models.BooleanField(default=False)),
                ('min_choices', models.PositiveIntegerField(default=0)),
                ('max_choices', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='restaurant.menuitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, default='', max_length=120)),
                ('extra_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='restaurant.menuoptiongroup')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=160)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('delivery_type', models.CharField(choices=[('collection', 'Recoger en tienda'), ('delivery', 'Entrega a domicilio')], default='collection', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('preparing', 'Preparando'), ('ready', 'Listo'), ('out_for_delivery', 'En reparto'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=30)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card_delivery', 'Tarjeta al repartidor'), ('online', 'Pago online'), ('store', 'Pagar en tienda')], default='cash', max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='pending', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=180)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('options_snapshot', models.JSONField(blank=True, default=list)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30)),
                ('provider', models.CharField(blank=True, default='', max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=160)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurant.order')),
            ],
        ),
    ]
