# Generated by Django 5.2.15 on 2026-06-10 21:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rider_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('amount', 'Fixed amount')], default='percent', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('first_order_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 means unlimited')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='Casa de Kebab Turco', max_length=180)),
                ('phone', models.CharField(default='+34 613 473 564', max_length=40)),
                ('address', models.CharField(default='Calle García Lorca, 1, Salamanca 37004', max_length=250)),
                ('is_open', models.BooleanField(default=True)),
                ('opening_hours', models.CharField(blank=True, default='12:00 - 23:30', max_length=180)),
                ('collection_enabled', models.BooleanField(default=True)),
                ('delivery_enabled', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=8)),
                ('minimum_delivery_order', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8)),
                ('free_delivery_minimum', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant settings',
                'verbose_name_plural': 'Restaurant settings',
            },
        ),
    ]
