# Generated by Django 5.2.15 on 2026-06-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_coupon_restaurantsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='route_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='route_duration_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='route_provider',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
