# Generated by Django 5.2.15 on 2026-06-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_smsgatewaymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsettings',
            name='opening_hours',
            field=models.CharField(blank=True, default='12:00 - 01:00', max_length=180),
        ),
    ]
