# Generated by Django 5.2.15 on 2026-06-13 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_restaurantsettings_opening_hours'),
        ('restaurant', '0006_sync_sms_gateway_fields'),
    ]

    operations = [
    ]
