# Generated by Django 6.0.5 on 2026-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_order_chat_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rider',
            name='username',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
