# Generated by Django 6.0.5 on 2026-06-15 04:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_orderreview_detailed_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('device_token', models.TextField(unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('app_version', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='restaurantfinancialentry',
            new_name='restaurant__entry_t_4d28cb_idx',
            old_name='restaurant__entry_t_2f323a_idx',
        ),
        migrations.RenameIndex(
            model_name='restaurantfinancialentry',
            new_name='restaurant__paid_by_0a956c_idx',
            old_name='restaurant__paid_by_415d48_idx',
        ),
        migrations.RemoveField(
            model_name='orderreview',
            name='admin_reply',
        ),
        migrations.RemoveField(
            model_name='orderreview',
            name='delivery_rating',
        ),
        migrations.RemoveField(
            model_name='orderreview',
            name='food_rating',
        ),
        migrations.RemoveField(
            model_name='orderreview',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='orderreview',
            name='packaging_rating',
        ),
        migrations.RemoveField(
            model_name='orderreview',
            name='rider_rating',
        ),
        migrations.RemoveField(
            model_name='orderreview',
            name='would_recommend',
        ),
        migrations.AddField(
            model_name='customerpushdevice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to='restaurant.customer'),
        ),
        migrations.AddIndex(
            model_name='customerpushdevice',
            index=models.Index(fields=['phone', 'is_active'], name='restaurant__phone_4754fd_idx'),
        ),
    ]
