# Generated by Django 6.0.5 on 2026-06-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_rider_push_device'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='riderpushdevice',
            new_name='restaurant__rider_i_55b525_idx',
            old_name='restaurant__rider_i_idx',
        ),
        migrations.AlterField(
            model_name='restaurantfinancialentry',
            name='entry_type',
            field=models.CharField(choices=[('expense', 'Gasto'), ('contribution', 'AportaciÃ³n a BBVA'), ('settlement', 'LiquidaciÃ³n entre socios')], db_index=True, default='expense', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='address',
            field=models.CharField(default='Calle GarcÃ\xada Lorca, 1, Salamanca 37004', max_length=250),
        ),
        migrations.AlterField(
            model_name='systembackup',
            name='backup_type',
            field=models.CharField(choices=[('database', 'Base de datos JSON'), ('configuration', 'ConfiguraciÃ³n'), ('media', 'Archivos Media')], db_index=True, max_length=30),
        ),
    ]
