# Generated by Django 6.0.5 on 2026-06-21 03:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_rename_restaurant__rider_i_idx_restaurant__rider_i_55b525_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('unit', models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('unit', 'Unidades')], default='g', max_length=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Coste por la unidad elegida: g, ml o unidad.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('fixed_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coste fijo adicional por unidad: servilletas, energía u otros.', max_digits=8)),
                ('target_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('55.00'), max_digits=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_profile', to='restaurant.menuitem')),
            ],
            options={
                'ordering': ['menu_item__name_es'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Cantidad usada por una unidad del producto, en la misma unidad del ingrediente.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_components', to='restaurant.ingredient')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='restaurant.productcostprofile')),
            ],
            options={
                'ordering': ['ingredient__name'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'ingredient'), name='unique_recipe_ingredient_per_profile')],
            },
        ),
    ]
