# Generated by Django 5.0.8 on 2026-07-01 01:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_ingredient_productcostprofile_recipeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpenseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='monthly', max_length=12)),
                ('paid_by', models.CharField(choices=[('saeid', 'Saeid'), ('ahmed', 'Ahmed'), ('bbva', 'Cuenta conjunta BBVA')], default='bbva', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('updated_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='restaurant.expensecategory')),
            ],
            options={
                'ordering': ['title', 'id'],
                'indexes': [models.Index(fields=['is_active', 'start_date'], name='restaurant__is_acti_24f6c7_idx')],
            },
        ),
    ]
