# Generated by Django 5.0.8 on 2026-07-01 01:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_recurringexpenserule'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Consumo por venta'), ('waste', 'Merma / desperdicio'), ('adjustment', 'Ajuste manual')], db_index=True, max_length=16)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=160)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('reference', models.CharField(blank=True, default='', max_length=180)),
                ('notes', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='restaurant.restaurantfinancialentry')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='restaurant.ingredient')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='restaurant.orderitem')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['ingredient', 'occurred_at'], name='restaurant__ingredi_d2dce8_idx'), models.Index(fields=['movement_type', 'occurred_at'], name='restaurant__movemen_11a922_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.UniqueConstraint(fields=('order_item', 'ingredient', 'movement_type'), name='unique_inventory_sale_per_order_item_ingredient_type'),
        ),
    ]
