# Generated by Django 5.0.8 on 2026-07-01 01:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_inventorymovement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_revenue_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monthly_profit_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business target',
                'verbose_name_plural': 'Business targets',
            },
        ),
    ]
