# Generated by Django 6.0.5 on 2026-07-05 15:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_inventory_purchase_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fridge_alert_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fridge_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_beverage',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='total_alert_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Consumo por venta'), ('waste', 'Merma / desperdicio'), ('adjustment', 'Ajuste manual'), ('fridge_transfer', 'Traslado al frigorífico')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='restaurantfinancialentry',
            name='entry_type',
            field=models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso manual'), ('contribution', 'AportaciÃ³n a BBVA'), ('settlement', 'LiquidaciÃ³n entre socios')], db_index=True, default='expense', max_length=20),
        ),
    ]
